export const PRODUCTS = 
[
    {
      title: "rings",
      name: "Ring",
      price: "350",
      oldPrice: "500",
      featured: true,
      image: "/assets/img/products/ring.png",
      discription: "discription",
      orderID: "SH101RI",
    },
    {
      title: "earrings",
      name: "Earring",
      price: "300",
      oldPrice: "400",
      featured: true,
      image: "/assets/img/products/ring.png",
      discription: "discription",
      orderID: "SH102EA",
    },
    {
      title: "earrings",
      name: "Earring",
      price: "300",
      oldPrice: "400",
      featured: true,
      image: "/assets/img/products/ring.png",
      discription: "discription",
      orderID: "SH102EA",
    },
    {
      title: "earrings",
      name: "Earring",
      price: "300",
      oldPrice: "400",
      featured: true,
      image: "/assets/img/products/ring.png",
      discription: "discription",
      orderID: "SH102EA",
    },
    {
      title: "earrings",
      name: "Earring",
      price: "300",
      oldPrice: "400",
      featured: true,
      image: "/assets/img/products/ring.png",
      discription: "discription",
      orderID: "SH102EA",
    },
    {
      title: "earrings",
      name: "Earring",
      price: "300",
      oldPrice: "400",
      featured: true,
      image: "/assets/img/products/ring.png",
      discription: "discription",
      orderID: "SH102EA",
    },
  ]